# Generated by Django 5.1.2 on 2024-10-16 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicProdDetails',
            fields=[
                ('idProductDetails', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('full_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=15)),
                ('full_address', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='MusicDiscography',
            fields=[
                ('idDiscography', models.AutoField(primary_key=True, serialize=False)),
                ('trackname', models.CharField(max_length=45)),
                ('music_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.musicproddetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('idOrderItems', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='musicproddetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.CreateModel(
            name='AudioProdDetails',
            fields=[
                ('idProductDetails', models.AutoField(primary_key=True, serialize=False)),
                ('neutral_sound', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sports', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gaming', models.DecimalField(decimal_places=1, max_digits=10)),
                ('review', models.CharField(max_length=600)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('idUserPayment', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=45)),
                ('provider', models.CharField(max_length=45)),
                ('account_no', models.CharField(max_length=45)),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
