# Generated by Django 5.1.3 on 2024-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioproddetails',
            old_name='idProductDetails',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='musicdiscography',
            old_name='idDiscography',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='musicproddetails',
            old_name='idProductDetails',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='idOrder',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='idOrderItems',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='idProduct',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idUser',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='idUserPayment',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
