# Generated by Django 5.1.3 on 2024-11-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_idproductdetails_audioproddetails_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_id',
        ),
    ]
