# Generated by Django 5.1.3 on 2024-11-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='descri',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwrd',
        ),
    ]
