# Generated by Django 4.2.16 on 2024-11-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_user_passwrd_user_last_login_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
